spring:
  application:
    name: JmusclesRestProducer
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - MDC: %mdc %msg%n"
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    com.jmuscles.rest.*: DEBUG
management:
   server:
      ssl:
         enabled: false
   endpoints:
      web:
#base-path: /sssactuator
         exposure:
            include: '*'        