server:
   port: 8081
spring:
   application:
      name: JmusclesRestProducer
#   rabbitmq:
#      addresses: host.docker.internal:5672
#      username: guest
#      password: guest
   rabbitmq:
      addresses: localhost:5672
      username: guest
      password: guest
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - MDC: %mdc %msg%n"
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    com.jmuscles.rest.*: DEBUG
management:
   server:
      ssl:
         enabled: false
   endpoints:
      web:
#base-path: /sssactuator
         exposure:
            include: '*'
jmuscles:
  async-producer-config:
     activeProducersInOrder: 
        - rabbitmq
        - syncProcessing
     rabbitmq: 
        defaultRoutingKey: DEMO_QUEUE
        defaultExchange: EXCHANGE_1
        nonPersistentDeliveryMode: false