 #--profile group/include are adding files from class path but not from confihg server, please pass it from run arguments
  #profiles:
    #group:
      #docker-local: rabbitmq-setup-local,executors-local,producer-local
      #local: rabbitmq-setup-local,executors-local,producer-local
      #dev: rabbitmq-setup-dev,executors-dev,producer-dev,datasource-dev
      #prod: rabbitmq-setup-prod,executors-prod,producer-prod,datasource-prod  
async-producer-config:
   activeProducersInOrder: 
      - rabbitmq
      - syncProcessing
   rabbitmq: 
      defaultRoutingKey: GENERIC_Q
      defaultExchange: AP_GENERIC_DIRECT_EXCHANGE
      nonPersistentDeliveryMode: false

rest-producer-config:
   countryInfoService_soap:
      responseBuilder: CountryInfoServiceResponseBuilder
      configByHttpMethods:
         POST:
            responseConfig:
               success:
                  status: 200
                  body: '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><DivideResponse xmlns="http://tempuri.org/"><DivideResult>1</DivideResult></DivideResponse></soap:Body></soap:Envelope>'
                  headers: 
                     Content-Type: text/xml
               failure:
                  status: 500
                  body: "failure"
                  headers: 
                     Content-Type: text/xml            
                     response-key1: response-error-value1
                     response-key2: response-error-value2
   numberConversion_soap:
      responseBuilder: SimpleResponseBuilder
      configByHttpMethods:
         POST:
            responseConfig:
               success:
                  status: 200
                  body: '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><DivideResponse xmlns="http://tempuri.org/"><DivideResult>1</DivideResult></DivideResponse></soap:Body></soap:Envelope>'
                  headers: 
                     Content-Type: text/xml
               failure:
                  status: 500
                  body: "failure"
                  headers: 
                     Content-Type: text/xml            
                     response-key1: response-error-value1
                     response-key2: response-error-value2
   isbnservice_soap:
      responseBuilder: SimpleResponseBuilder
      configByHttpMethods:
         POST:
            responseConfig:
               success:
                  status: 200
                  body: '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><DivideResponse xmlns="http://tempuri.org/"><DivideResult>1</DivideResult></DivideResponse></soap:Body></soap:Envelope>'
                  headers: 
                     Content-Type: text/xml
               failure:
                  status: 500
                  body: "failure"
                  headers: 
                     Content-Type: text/xml            
   calculator_soap:
      configByHttpMethods:
         POST:
            responseConfig:
               failure:
                  status: 500
                  body: "failure"
                  headers: 
                     Content-Type: text/xml            
   tempconvert_soap:
      configByHttpMethods:
         POST:
            responseConfig:
               success:
                  status: 200
                  body: '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><DivideResponse xmlns="http://tempuri.org/"><DivideResult>1</DivideResult></DivideResponse></soap:Body></soap:Envelope>'
                  headers: 
                     Content-Type: text/xml
               failure:
                  status: 500
                  body: "failure"
                  headers: 
                     Content-Type: text/xml            
   restcountries:
      responseBuilder: SimpleResponseBuilder
      configByHttpMethods:
         POST:
            responseConfig:
               success:
                  status: 200
                  body: 'message successfully queued to be processed'
                  headers: 
                     Content-Type: application/json
               failure:
                  status: 500
                  body: "failure"
                  headers: 
                     Content-Type: application/json            
   jsonplaceholderpost:
      responseBuilder: SimpleResponseBuilder
      configByHttpMethods:
         POST:
            responseConfig:
               success:
                  status: 200
                  body: 'message successfully queued to be processed'
                  headers: 
                     Content-Type: application/json
               failure:
                  status: 500
                  body: "failure"
                  headers: 
                     Content-Type: application/json            

   reqres:
      responseBuilder: SimpleResponseBuilder
      configByHttpMethods:
         POST:
            responseConfig:
               success:
                  status: 200
                  body: 'message successfully queued to be processed'
                  headers: 
                     Content-Type: application/json
               failure:
                  status: 500
                  body: "failure"
                  headers: 
                     Content-Type: application/json            
   getDemoUser:
      configByHttpMethods:
         GET:
            processingConfig:
               activeProducersInOrder:
                  - rabbitmq
                  - syncProcessing    
               rabbitmq: 
                  defaultRoutingKey: DEMO_QUEUE
                  defaultExchange: EXCHANGE_1
                  nonPersistentDeliveryMode: false
            responseConfig:
               success:
                  status: 200
                  body: "success"
                  headers: 
                     Content-Type:  text/html
                     response-key1: response-value1
                     response-key2: response-value2
                     response-key3: response-value3
                     response-key4: response-value4
                     response-key5: response-value5            
               failure:
                  status: 500
                  body: "failure"
                  headers: 
                     response-key1: response-error-value1
                     response-key2: response-error-value2
                     response-key3: response-error-value3
                     response-key4: response-error-value4
                     response-key5: response-error-value5
jmuscles:
   executors-config:
      restConfig:
         connectionTimeout: 10000
         readTimeout: 10000
      restCalls:
         test:
            url: http://localhost:8080/place/list/IN
            successCodePatterns:
               200: null
         getDemoUser:
            url: https://gorest.co.in/public/v1/users
            successCodePatterns:
               200: null
         createDemoUser:
            url: https://gorest.co.in/public/v1/users
            successCodePatterns:
               200: null
               401: null
      sqlProcedures:
         demo_proc_1:
            dskey: null
            procedure: procedure_name
            successKey: P_RESP_CODE
            successValue: '000'
      sqlQueries:
         insert_user_testdb:
            dskey: testdb
            query: insert into test.user(user_id, first_name, last_name, email, gender) values(:user_id, :first_name, :last_name,
               :email, :gender);
            successResponse: null